# Don't print a new line at the start of the prompt
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"

[directory]
read_only = " "

[cmd_duration]
format = "[祥$duration]($style)"

[shlvl]
disabled = false
format = "[$symbol$shlvl ]($style)"
symbol = "↕️"
threshold = 1

#[username]
#show_always = true

#[jobs]
#disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
display_private = true

# Don't separate the prompt into two lines
[line_break]
disabled = false

# Don't show battery charge
[battery]
disabled = true
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
format = "@ [$symbol$branch]($style) "
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = ""

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
python_binary = "python3"
style = "green bold"
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

